export const GET_AUTH_STATE = "GET_AUTH_STATE";
export const GOOGLE_AUTH_LOGIN = "GOOGLE_AUTH_LOGIN";
export const GOOGLE_AUTH_LOGOUT = "GOOGLE_AUTH_LOGOUT";
export const CREATE_STREAM = "CREATE_STREAM";
export const DELETE_STREAM = "DELETE_STREAM";
export const EDIT_STREAM = "EDIT_STREAM";
export const FETCH_STREAMS = "FETCH_STREAMS";
export const FETCH_STREAM = "FETCH_STREAM";
